# permissions for end users to view distributedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributedsecrets-viewer-role
rules:
- apiGroups:
  - distributed-secrets.distributed-secrets.com
  resources:
  - distributedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - distributed-secrets.distributed-secrets.com
  resources:
  - distributedsecrets/status
  verbs:
  - get
