# permissions for end users to edit distributedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributedsecrets-editor-role
rules:
- apiGroups:
  - distributed-secrets.distributed-secrets.com
  resources:
  - distributedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distributed-secrets.distributed-secrets.com
  resources:
  - distributedsecrets/status
  verbs:
  - get
