---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - distributed-secrets.distributed-secrets.com
  resources:
  - distributedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distributed-secrets.distributed-secrets.com
  resources:
  - distributedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - distributed-secrets.distributed-secrets.com
  resources:
  - distributedsecrets/status
  verbs:
  - get
  - patch
  - update
